/*
 * This file is generated by jOOQ.
 */
package diplomski.xapi.jooq.model.tables.records;


import diplomski.xapi.jooq.model.tables.Course;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CourseRecord extends UpdatableRecordImpl<CourseRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -1926861383;

    /**
     * Setter for <code>public.COURSE.name</code>.
     */
    public void setName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.COURSE.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.COURSE.id</code>.
     */
    public void setId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.COURSE.id</code>.
     */
    public String getId() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Course.COURSE.NAME;
    }

    @Override
    public Field<String> field2() {
        return Course.COURSE.ID;
    }

    @Override
    public String component1() {
        return getName();
    }

    @Override
    public String component2() {
        return getId();
    }

    @Override
    public String value1() {
        return getName();
    }

    @Override
    public String value2() {
        return getId();
    }

    @Override
    public CourseRecord value1(String value) {
        setName(value);
        return this;
    }

    @Override
    public CourseRecord value2(String value) {
        setId(value);
        return this;
    }

    @Override
    public CourseRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CourseRecord
     */
    public CourseRecord() {
        super(Course.COURSE);
    }

    /**
     * Create a detached, initialised CourseRecord
     */
    public CourseRecord(String name, String id) {
        super(Course.COURSE);

        set(0, name);
        set(1, id);
    }
}
