/*
 * This file is generated by jOOQ.
 */
package diplomski.xapi.jooq.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CoursePages implements Serializable {

    private static final long serialVersionUID = 933918053;

    private Integer pagenumber;
    private String  datatext;
    private String  courseid;

    public CoursePages() {}

    public CoursePages(CoursePages value) {
        this.pagenumber = value.pagenumber;
        this.datatext = value.datatext;
        this.courseid = value.courseid;
    }

    public CoursePages(
        Integer pagenumber,
        String  datatext,
        String  courseid
    ) {
        this.pagenumber = pagenumber;
        this.datatext = datatext;
        this.courseid = courseid;
    }

    public Integer getPagenumber() {
        return this.pagenumber;
    }

    public void setPagenumber(Integer pagenumber) {
        this.pagenumber = pagenumber;
    }

    public String getDatatext() {
        return this.datatext;
    }

    public void setDatatext(String datatext) {
        this.datatext = datatext;
    }

    public String getCourseid() {
        return this.courseid;
    }

    public void setCourseid(String courseid) {
        this.courseid = courseid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CoursePages (");

        sb.append(pagenumber);
        sb.append(", ").append(datatext);
        sb.append(", ").append(courseid);

        sb.append(")");
        return sb.toString();
    }
}
