/*
 * This file is generated by jOOQ.
 */
package diplomski.xapi.jooq.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Quiz implements Serializable {

    private static final long serialVersionUID = -2033674909;

    private String id;

    public Quiz() {}

    public Quiz(Quiz value) {
        this.id = value.id;
    }

    public Quiz(
        String id
    ) {
        this.id = id;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Quiz (");

        sb.append(id);

        sb.append(")");
        return sb.toString();
    }
}
