/*
 * This file is generated by jOOQ.
 */
package diplomski.xapi.jooq.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuizPages implements Serializable {

    private static final long serialVersionUID = -90093195;

    private Integer page;
    private String  question;
    private String  quizid;
    private String  answer;

    public QuizPages() {}

    public QuizPages(QuizPages value) {
        this.page = value.page;
        this.question = value.question;
        this.quizid = value.quizid;
        this.answer = value.answer;
    }

    public QuizPages(
        Integer page,
        String  question,
        String  quizid,
        String  answer
    ) {
        this.page = page;
        this.question = question;
        this.quizid = quizid;
        this.answer = answer;
    }

    public Integer getPage() {
        return this.page;
    }

    public void setPage(Integer page) {
        this.page = page;
    }

    public String getQuestion() {
        return this.question;
    }

    public void setQuestion(String question) {
        this.question = question;
    }

    public String getQuizid() {
        return this.quizid;
    }

    public void setQuizid(String quizid) {
        this.quizid = quizid;
    }

    public String getAnswer() {
        return this.answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("QuizPages (");

        sb.append(page);
        sb.append(", ").append(question);
        sb.append(", ").append(quizid);
        sb.append(", ").append(answer);

        sb.append(")");
        return sb.toString();
    }
}
