/*
 * This file is generated by jOOQ.
 */
package diplomski.xapi.jooq.model;


import diplomski.xapi.jooq.model.tables.Course;
import diplomski.xapi.jooq.model.tables.CoursePages;
import diplomski.xapi.jooq.model.tables.Quiz;
import diplomski.xapi.jooq.model.tables.QuizPages;
import diplomski.xapi.jooq.model.tables.records.CoursePagesRecord;
import diplomski.xapi.jooq.model.tables.records.CourseRecord;
import diplomski.xapi.jooq.model.tables.records.QuizPagesRecord;
import diplomski.xapi.jooq.model.tables.records.QuizRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CourseRecord> COURSE_PKEY = UniqueKeys0.COURSE_PKEY;
    public static final UniqueKey<QuizRecord> QUIZ_PKEY = UniqueKeys0.QUIZ_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CoursePagesRecord, CourseRecord> COURSE_PAGES__FCOURSE = ForeignKeys0.COURSE_PAGES__FCOURSE;
    public static final ForeignKey<QuizPagesRecord, QuizRecord> QUIZ_PAGES__FKQUIZID = ForeignKeys0.QUIZ_PAGES__FKQUIZID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<CourseRecord> COURSE_PKEY = Internal.createUniqueKey(Course.COURSE, "COURSE_pkey", new TableField[] { Course.COURSE.ID }, true);
        public static final UniqueKey<QuizRecord> QUIZ_PKEY = Internal.createUniqueKey(Quiz.QUIZ, "QUIZ_pkey", new TableField[] { Quiz.QUIZ.ID }, true);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<CoursePagesRecord, CourseRecord> COURSE_PAGES__FCOURSE = Internal.createForeignKey(Keys.COURSE_PKEY, CoursePages.COURSE_PAGES, "fCourse", new TableField[] { CoursePages.COURSE_PAGES.COURSEID }, true);
        public static final ForeignKey<QuizPagesRecord, QuizRecord> QUIZ_PAGES__FKQUIZID = Internal.createForeignKey(Keys.QUIZ_PKEY, QuizPages.QUIZ_PAGES, "fkQuizId", new TableField[] { QuizPages.QUIZ_PAGES.QUIZID }, true);
    }
}
