/*
 * This file is generated by jOOQ.
 */
package diplomski.xapi.jooq.model;


import diplomski.xapi.jooq.model.tables.Course;
import diplomski.xapi.jooq.model.tables.CoursePages;
import diplomski.xapi.jooq.model.tables.Quiz;
import diplomski.xapi.jooq.model.tables.QuizPages;
import diplomski.xapi.jooq.model.tables.User;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -422731640;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.COURSE</code>.
     */
    public final Course COURSE = Course.COURSE;

    /**
     * The table <code>public.COURSE_PAGES</code>.
     */
    public final CoursePages COURSE_PAGES = CoursePages.COURSE_PAGES;

    /**
     * The table <code>public.QUIZ</code>.
     */
    public final Quiz QUIZ = Quiz.QUIZ;

    /**
     * The table <code>public.QUIZ_PAGES</code>.
     */
    public final QuizPages QUIZ_PAGES = QuizPages.QUIZ_PAGES;

    /**
     * The table <code>public.USER</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Course.COURSE,
            CoursePages.COURSE_PAGES,
            Quiz.QUIZ,
            QuizPages.QUIZ_PAGES,
            User.USER);
    }
}
