/*
 * This file is generated by jOOQ.
 */
package diplomski.xapi.jooq.model;


import diplomski.xapi.jooq.model.tables.Course;
import diplomski.xapi.jooq.model.tables.CoursePages;
import diplomski.xapi.jooq.model.tables.Quiz;
import diplomski.xapi.jooq.model.tables.QuizPages;
import diplomski.xapi.jooq.model.tables.User;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.COURSE</code>.
     */
    public static final Course COURSE = Course.COURSE;

    /**
     * The table <code>public.COURSE_PAGES</code>.
     */
    public static final CoursePages COURSE_PAGES = CoursePages.COURSE_PAGES;

    /**
     * The table <code>public.QUIZ</code>.
     */
    public static final Quiz QUIZ = Quiz.QUIZ;

    /**
     * The table <code>public.QUIZ_PAGES</code>.
     */
    public static final QuizPages QUIZ_PAGES = QuizPages.QUIZ_PAGES;

    /**
     * The table <code>public.USER</code>.
     */
    public static final User USER = User.USER;
}
